added three new rpc tests - two for Sapling and one for getNormalizedScript
ecadlabs/taquito pull request #1369
Opened 2022-01-28 18:52 UTC by michaelkernaghan

Closes #1356 1356

2022-01-31 17:05 UTC, roxaneletourneau requested changes

2022-01-31 17:05 UTC, roxaneletourneau commented on integration-tests/contract-originate-contract-with-sapling.spec.ts
> +      console.log("Sapling Contract address "+contract.address)
console.log can be removed

2022-02-01 15:01 UTC, michaelkernaghan commented on integration-tests/config.ts
> +  rpc: process.env['TEZOS_RPC_HANGZHOUNET'] || 'http://10.60.41.80:8732/',
restored

2022-02-01 15:12 UTC, michaelkernaghan commented on integration-tests/contract-originate-contract-with-sapling.spec.ts
> +      console.log("Sapling Contract address "+contract.address)
ooops thanks :) removed.

2022-02-01 15:43 UTC, michaelkernaghan commented on integration-tests/config.ts
> +  rpc: process.env['TEZOS_RPC_ITHACANET'] || 'http://ecad-ithacanet-full.i.tez.ie:8732/',
fixed

2022-02-01 17:31 UTC, michaelkernaghan commented on integration-tests/rpc-nodes.spec.ts
> +        it(`Access the script of the contract and normalize it using the requested unparsing mode`, async (done) => {
removed

2022-02-01 19:02 UTC, merged