Liquidity baking doc and permit integration tests
ecadlabs/taquito pull request #1402
Opened 2022-02-10 18:33 UTC by claudebarde

This pull request includes the new documentation for the liquidity baking contract and the update of the code for the permit integration tests.

2022-02-11 15:42 UTC, michaelkernaghan commented on integration-tests/contract-permits.spec.ts
> +  // const sigParamPacked = await Tezos.rpc.packData({
can the commented-out code that is not an instruction to the user be removed?

2022-02-11 15:42 UTC, michaelkernaghan commented on integration-tests/contract-permits.spec.ts
> +      /*const bytes_to_sign = await permit_contract.methods
is this commented out?

2022-02-15 08:33 UTC, claudebarde commented on integration-tests/contract-permits.spec.ts
> +      /*const bytes_to_sign = await permit_contract.methods
Yes, I updated the PR and removed the commented-out code

2022-02-15 17:58 UTC, roxaneletourneau commented on docs/liquidity_baking.md
> +      return xtzPool.plus(new BigNumber(2500000));
To clarify what the 2500000 refers to, consider defining a constant (ie: liquidityBakingSubsidy = 2500000)

2022-02-17 08:24 UTC, claudebarde commented on docs/liquidity_baking.md
> +        .plus(new BigNumber(tokenIn).times(new BigNumber(999000)));
This function was adapted from this code: https://gitlab.com/sophiagold/dexter-calculations/-/blob/liquidity_baking/index-raw.js#L390, I have no idea what 999000 is but I trust the great minds that wrote this code 😅

2022-02-23 16:46 UTC, roxaneletourneau commented on docs/liquidity_baking.md
> +        .plus(new BigNumber(tokenIn).times(new BigNumber(999000)));
> the formula is (1 - burnFee) * (tezPool * tokenAmount * (1 - dexFee) / (tokenPool + tokenAmount * (1 - dexFee)))

2022-02-25 00:29 UTC, roxaneletourneau requested changes

2022-02-25 00:29 UTC, roxaneletourneau commented on docs/liquidity_baking.md
> +const batchOp = await $store.Tezos.wallet
`$store.` should be removed

2022-03-01 16:43 UTC, claudebarde commented on docs/liquidity_baking.md
> +const batchOp = await $store.Tezos.wallet
Removed!

2022-03-01 18:19 UTC, merged