Added support for Jakarta tx rollup rpc endpoints in RPC client
ecadlabs/taquito pull request #1651
Opened 2022-05-25 21:58 UTC by dsawali

#1617 

- Updated rpc client to support new tx rollup endpoints
- Updated unit tests
- Updated types 

Thank you for your contribution to Taquito.

Before submitting this PR, please make sure:

- [ ] Your code builds cleanly without any errors or warnings
- [ ] You have added unit tests
- [ ] You have added integration tests (if relevant/appropriate)
- [ ] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [ ] You have added or updated corresponding documentation
- [ ] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

## Release Note Draft Snippet

__If relevant, please write a summary of your change that will be suitable for
inclusion in the Release Notes for the next Taquito release.__

2022-05-25 23:32 UTC, roxaneletourneau reviewed
Could you add integration tests in the rpc-nodes.spec.ts file?

2022-05-25 23:40 UTC, roxaneletourneau requested changes

2022-05-25 23:40 UTC, roxaneletourneau commented on packages/taquito-rpc/src/types.ts
> +  last_removed_commitment_hashes: LastRemovedCommitmentHashes;
Can last_removed_commitment_hashes be optional?

2022-05-25 23:40 UTC, roxaneletourneau commented on packages/taquito-rpc/src/types.ts
> +  finalized_commitments: Next;
Missing some properies:
```
 "next": integer ∈ [-2^31-1, 2^31] }
      || { /* interval */
           "newest": integer ∈ [-2^31-1, 2^31],
           "oldest": integer ∈ [-2^31-1, 2^31] },
```

2022-05-25 23:40 UTC, roxaneletourneau commented on packages/taquito-rpc/src/types.ts
> +  unfinalized_commitments: Next;
some comment as for finalized_commitments

2022-05-25 23:40 UTC, roxaneletourneau commented on packages/taquito-rpc/src/types.ts
> +  commitment_newest_hash: string;
Can commitment_newest_hash be optional?

2022-05-25 23:40 UTC, roxaneletourneau commented on packages/taquito-rpc/src/types.ts
> +  tezos_head_level: number;
optional?

2022-05-25 23:40 UTC, roxaneletourneau commented on packages/taquito-rpc/src/types.ts
> +  commitments_watermark: number;
optional?

2022-05-26 16:08 UTC, dsawali commented on packages/taquito-rpc/src/taquito-rpc.ts
> +  async getTxRollupInbox(
we could try adding a ` | null` in the return type in this case

2022-05-27 20:37 UTC, dsawali commented on packages/taquito-rpc/src/rpc-client-interface.ts
> +  GET_BAKING_RIGHTS = 'getBakingRights',
I think the quote changes were made by the linter, do you think this would pose an issue? @roxaneletourneau

2022-05-27 22:02 UTC, roxaneletourneau reviewed
Good work :)

2022-05-27 22:03 UTC, dsawali commented on integration-tests/rpc-nodes.spec.ts
> +        jakartanetIt('getTxRollupInbox', async (done) => {
that's a good idea, I'll add mondaynet

2022-05-30 18:23 UTC, roxaneletourneau approved these changes

2022-05-30 18:28 UTC, merged