Multisig documentation
ecadlabs/taquito pull request #2033
Opened 2022-10-17 15:02 UTC by claudebarde

Added documentation for multisig contract interaction and reordered the doc chapters in the sidebar

2022-10-18 13:40 UTC, claudebarde commented on docs/multisig_doc.md
> +const lambda = `{
I know, that's where I got it from 😅 I thought it would be more interesting to expose the lambda here to show how it is constructed with the different values, what do you think?

2022-10-18 15:15 UTC, roxaneletourneau commented on docs/multisig_doc.md
> +const lambda = `{
Yes I think it is perfect to expose the lambda, but I was thinking that we can add a note about the `MANAGER_LAMBDA.transferImplicit` telling the users that they don't have to write the lambda themself and can only import it instead. What do you think? :)

2022-10-19 14:33 UTC, claudebarde commented on docs/multisig_doc.md
> +const lambda = `{
Actually, I only need the lambda here, I don't need to forge the operation, is it possible to import the lambda alone? I tried to look into the folders in the Taquito repo and there are too many of them, I couldn't guess where it is 😅

2022-10-19 17:12 UTC, roxaneletourneau commented on docs/multisig_doc.md
> +const lambda = `{
This `MANAGER_LAMBDA.transferImplicit("tz1eY5Aqa1kXDFoiebL28emyXFoneAoVg1zh", 500)` returns the lambda actually.

2022-10-20 09:54 UTC, claudebarde commented on docs/multisig_doc.md
> +const lambda = `{
Perfect, I updated the doc to mention the `MANAGER_LAMBDA`

2022-10-21 12:48 UTC, claudebarde commented on docs/multisig_doc.md
> +First, we write the Michelson lambda that will be executed to transfer the tez, where `RECIPIENT_ADDRESS` is the public key of the recipient of the tez and `AMOUNT` is the amount of tez to be sent.
`RECIPIENT_ADDRESS` is for the public key (as in the text), however `AMOUNT` is for mutez, not tez, I corrected it, thanks!

2022-10-21 12:49 UTC, claudebarde commented on docs/multisig_doc.md
> +const lambda = `{
It's been added!

2022-10-21 17:03 UTC, roxaneletourneau commented on docs/multisig_doc.md
> +First, we write the Michelson lambda that will be executed to transfer the tez, where `RECIPIENT_ADDRESS` is the public key of the recipient of the tez and `AMOUNT` is the amount of tez to be sent.
It is key_hash in the lambda, so I thought it needed a public key hash rather than public key

2022-10-24 17:08 UTC, claudebarde commented on docs/multisig_doc.md
> +First, we write the Michelson lambda that will be executed to transfer the tez, where `RECIPIENT_ADDRESS` is the public key of the recipient of the tez and `AMOUNT` is the amount of tez to be sent.
My bad, I got a little mixed up, correcting it right now, thank you!

2022-10-25 16:10 UTC, jevonearth commented on yarn.lock
> +@taquito/ledger-signer@file:/Users/zainensuzuki/code/taquito/packages/taquito-ledger-signer":
:eyes:

2022-10-27 15:30 UTC, roxaneletourneau requested changes

2022-10-27 15:30 UTC, roxaneletourneau commented on website/.gitignore
> +package-lock.json
package-lock.json should not be added to the `website/.gitignore` because when we add or update a new dependency, we have to commit it.

2022-10-27 16:00 UTC, claudebarde commented on website/.gitignore
> +package-lock.json
No problem, it's been updated!

2022-10-27 17:41 UTC, merged