2066 support types for new operations in lima
ecadlabs/taquito pull request #2097
Opened 2022-11-04 01:11 UTC by hui-an-yang

Thank you for your contribution to Taquito.

Before submitting this PR, please make sure:

- [ ] Your code builds cleanly without any errors or warnings
- [ ] You have added unit tests
- [ ] You have added integration tests (if relevant/appropriate)
- [ ] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [ ] You have added or updated corresponding documentation
- [ ] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

## Release Note Draft Snippet

__If relevant, please write a summary of your change that will be suitable for
inclusion in the Release Notes for the next Taquito release.__

2022-11-16 19:51 UTC, roxaneletourneau requested changes
minor comments, lgtm otherwise :)

2022-11-16 19:51 UTC, roxaneletourneau commented on packages/taquito-rpc/test/taquito-rpc.spec.ts
> +    it('should be able to access the properties of internal operation type event, proto15', async (done) => {
wrong test title

2022-11-16 19:51 UTC, roxaneletourneau commented on packages/taquito-rpc/test/taquito-rpc.spec.ts
> +    it('should be able to access the properties of internal operation type event, proto15', async (done) => {
wrong test title

2022-11-16 23:52 UTC, hui-an-yang commented on packages/taquito-rpc/test/taquito-rpc.spec.ts
> +    it('should be able to access the properties of internal operation type event, proto15', async (done) => {
addressed in a new commit

2022-11-16 23:52 UTC, hui-an-yang commented on packages/taquito-rpc/test/taquito-rpc.spec.ts
> +    it('should be able to access the properties of internal operation type event, proto15', async (done) => {
addressed in a new commit

2022-11-17 00:11 UTC, roxaneletourneau approved these changes

2022-11-17 22:49 UTC, merged