2307 smart rollup types
ecadlabs/taquito pull request #2324
Opened 2023-01-27 23:09 UTC by zainen

add type support for 
Smart_rollup_originate
Smart_rollup_add_messages
Smart_rollup_execute_outbox_message

added test suites with mock data pull from chain

closes #2307 

Thank you for your contribution to Taquito.

Before submitting this PR, please make sure:

- [x] Your code builds cleanly without any errors or warnings
- [x] You have run the linter against the changes
- [x] You have added unit tests (if relevant/appropriate)
- [ ] You have added integration tests (if relevant/appropriate)
- [ ] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [ ] You have added or updated corresponding documentation
- [ ] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

In this PR, please also make sure: 

- [x] You have linked this PR to the issue by putting `closes #TICKETNUMBER` in the description box (when applicable)
- [ ] You have added a concise description on your changes
## Release Note Draft Snippet

__If relevant, please write a summary of your change that will be suitable for
inclusion in the Release Notes for the next Taquito release.__

2023-01-27 23:11 UTC, zainen commented on packages/taquito-rpc/test/taquito-rpc.spec.ts
> +            ] as OperationMetadataBalanceUpdates[])
was changed because i got a weird error for type conflicts that seemed unreleated to my changes

2023-01-30 20:21 UTC, dsawali requested changes

2023-01-30 20:24 UTC, zainen commented on packages/taquito-rpc/src/types.ts
> +  parameters_ty: Record<string | number | symbol, unknown>;
![image](https://user-images.githubusercontent.com/72581075/215586950-a1d65e18-e8c5-4e4f-b7b4-98cf712513a3.png)
ooo ok i was sure with the empty object was supposed to represent

2023-01-30 22:44 UTC, dsawali approved these changes

2023-01-30 22:47 UTC, merged