2409 remaining smart rollup operation types
ecadlabs/taquito pull request #2415
Opened 2023-03-30 00:13 UTC by zainen

Thank you for your contribution to Taquito.

Before submitting this PR, please make sure:

- [ ] Your code builds cleanly without any errors or warnings
- [ ] You have run the linter against the changes
- [ ] You have added unit tests (if relevant/appropriate)
- [ ] You have added integration tests (if relevant/appropriate)
- [ ] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [ ] You have added or updated corresponding documentation
- [ ] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

In this PR, please also make sure: 

- [ ] You have linked this PR to the issue by putting `closes #TICKETNUMBER` in the description box (when applicable)
- [ ] You have added a concise description on your changes
## Release Note Draft Snippet

__If relevant, please write a summary of your change that will be suitable for
inclusion in the Release Notes for the next Taquito release.__

2023-03-31 21:16 UTC, dsawali requested changes

2023-03-31 21:16 UTC, dsawali commented on packages/taquito-rpc/src/types.ts
> +  balance_updates: OperationBalanceUpdates;
these all should be optional except for status

2023-03-31 21:16 UTC, dsawali commented on packages/taquito-rpc/src/types.ts
> +  inbox_level: number;
same comment

2023-03-31 21:16 UTC, dsawali commented on packages/taquito-rpc/src/types.ts
> +  balance_updates: OperationBalanceUpdates;
same comment

2023-03-31 21:16 UTC, dsawali commented on packages/taquito-rpc/src/types.ts
> +  balance_updates: OperationBalanceUpdates;
this too

2023-03-31 21:16 UTC, dsawali commented on packages/taquito-rpc/src/types.ts
> +  balance_updates: OperationBalanceUpdates;
same comment

2023-03-31 21:16 UTC, dsawali commented on packages/taquito-rpc/test/data/rpc-responses.ts
> +export const smartRollupCementSample = {
could you rename these to `smartRollupCementResponse` like the other examples for consistency? 

same with the other additional smart rollup operations

2023-04-03 22:05 UTC, dsawali commented
could you link the issue to the PR please

2023-04-05 17:42 UTC, AlirezaHaghshenas commented on packages/taquito-rpc/test/taquito-rpc.spec.ts
> +        .contents[0] as OperationContentsAndResultSmartRollupPublish;
Regarding the conversation we had about avoiding casting, we can modify this code to make sure that type narrowing works well for our types and users can avoid casting.

```
const content = response.operations[0][0].contents[0]; // no casting here
// test fields that are common here
if (content.kind !== OpKind.SMART_ROLLUP_PUBLISH) {
  fail('Some message');
  return; //maybe this is not needed.
}
// test fields that are only specific to OperationContentsAndResultSmartRollupPublish
```

2023-04-06 21:07 UTC, dsawali approved these changes

2023-04-06 21:23 UTC, merged